---
Description: A webserver (LAP)
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.nano
    Description: EC2 Instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: cf-vpc-kp
    AllowedValues:
      - cf-vpc-kp
    Description: Key Pair Name
  InstanceName:
    Type: String
    Default: Basic Webserver
  Subnet:
    Type: String
    Default: tvpc-private-subnet-1
    AllowedValues:
      - tvpc-private-subnet-1
      - tvpc-public-subnet-1
      - tvpc-private-subnet-2
  VPC:
    Type: String
    Default: tvpc

Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.small:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0080e4c5bc078760e

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds: 
        - !ImportValue ws-sg
      KeyName: !Ref KeyName
      ImageId: !FindInMap [ AWSRegionArch2AMI, !Ref 'AWS::Region' , !FindInMap [ AWSInstanceType2Arch, !Ref InstanceType, Arch ] ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install httpd -y
          service httpd start
          chkconfig httpd on
          echo "<html><body><h1>Hellow from Server ${AWS::Region}</h1></body></html>" > /var/www/html/index.html
      Tags:
        -
          Key: Name
          Value: !Ref InstanceName
      SubnetId: 
        Fn::ImportValue:
          !Sub "${Subnet}"